apiVersion: v1
kind: Service # Kubernetes resource that exposes a set of Pods as a network service
metadata:
  name: wil-service
  namespace: dev
spec:
  selector:
    app: wil-playground # Selects the 'playground' Pods labels created by Deployment
  ports:
    - protocol: TCP # TCP By default if not set : tells kube-proxy how to route packets
      port: 8888 # The port on which the Service is exposed inside the cluster
      targetPort: 8888 # The port on the Pod's container that receives the traffic; usually matches containerPort but doesn't have to
  type: LoadBalancer # In K3d, this will map the Service port to a host port using the built-in Traefik, even without an external cloud provider.

